### ISSUE TITLE
BetterBankRemake Error

### ISSUE THREAD

**Issue by Gold14567** [WiroWorks/BetterBankRemake#1]
[script:BetterBankRem] SCRIPT ERROR: @BetterBankRemake/server.lua:147: attempt to call a nil value (field 'getAccount')
[script:BetterBankRem] > TriggerServerCallback (@es_extended/server/functions.lua:172)
[script:BetterBankRem] > handler (@es_extended/server/common.lua:114)

**Comment by WiroWorks** [comment]
Have you fixed the issue ?
