### ISSUE TITLE
ESX Legacy Fix

### ISSUE THREAD

**Issue by Gold14567** [WiroWorks/BetterBankRemake#2]
[server.zip](https://github.com/WiroWorks/BetterBankRemake/files/9995051/server.zip)

**Comment by Gold14567** [comment]
this is for getAccount type error

**Comment by WiroWorks** [comment]
Hello, this error might be depends on your es_extended script. Because as i know ESX is using camelcase methods in thier methods and functions. In server.lua file that you send it, its writing "getaccount" but it must be "getAccount". Its strange to you get that error and fix it like that.

**Comment by Gold14567** [comment]
yeah i fix it and found more error and fixed them too 
[BetterBankRemake.zip](https://github.com/WiroWorks/BetterBankRemake/files/9995093/BetterBankRemake.zip)

**Comment by Gold14567** [comment]
i want to translate it to turkish how can i do that

**Comment by WiroWorks** [comment]
Just translate the english strings to turkish. But if you don't know what are you doing rather don't.
